// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NavController from "./nav_controller";
import trainorsController from './trainors_controller';

application.register("nav", NavController)
application.register('trainor', trainorsController)
